### PR TITLE
Jmorton review 1

### PR DESCRIPTION
**Pull request by Dasepho**
@joe9599 and I have reviewed. We think this is ready to ship now

### CODE REVIEW

**Comment by joe9599** [comment]
We are unsure of the order of labs, and at one point it was mentioned that the ultrasound section may be done in hardware rather than detecting distance in software, but nothing more has been said about this in a while, so it is assumed that it is not happening for Smallpeice 2019

**Comment by jcwilliamson** [comment]
@joe9599  as far as I'm aware, the current plan is to have the software calculate a distance, then the students can calculate range from that. @antonnikitin97 probably knows a little bit more about that than me.

**Comment by trickeydan** [comment]
:shipit:

**Comment by Dasepho** [comment]
@joe9599 are you happy to delete the branch now that it has been merged?

**Comment by joe9599** [comment]
I don't really know how this stuff works, so if you are happy it's merged, then feel free to delete it

**Comment by trickeydan** [comment]
For future reference @joe9599, if a branch has been merged, it's generally best practice to delete it. On a lot of the software repos, we even have a bot who does it for us!

**Pull request merged**
